import type { ComponentType } from "react";
import {
  SiJavascript,
  SiTypescript,
  SiPython,

  SiCplusplus,
  SiSharp,
  SiGo,
  SiRust,
  SiKotlin,
  SiSwift,
  SiPhp,
  SiRuby,
  SiDart,
  SiScala,
  SiPerl,
  SiR,
  SiLua,
  SiJulia,
  SiHaskell,
  SiElixir,
  SiErlang,
  SiClojure,
  SiFsharp,
  SiOcaml,
  SiFortran,
  SiSolidity,
  SiNim,
  SiZig,
  SiGrocy as SiGroovy,

  SiHtml5,
  SiCss,
  SiSass,
  SiMysql,
  SiGraphql,
  SiNodedotjs,
  SiReact,
  SiVuedotjs,
  SiAngular,
  SiSvelte,
  SiDocker,
  SiYaml,
  SiJson,
  SiMarkdown,
  SiGnubash,
  SiOpenjdk,
} from "react-icons/si";
import { FileCode2 } from "lucide-react";

type IconType = ComponentType<any>;


const ICONS: Record<string, IconType> = {
  javascript: SiJavascript,
  jsx: SiReact,
  typescript: SiTypescript,
  tsx: SiReact,
  python: SiPython,
  java: SiOpenjdk,
  c: FileCode2,
  cpp: SiCplusplus,
  csharp: SiSharp,
  fsharp: SiFsharp,
  go: SiGo,
  rust: SiRust,
  kotlin: SiKotlin,
  swift: SiSwift,
  php: SiPhp,
  ruby: SiRuby,
  dart: SiDart,
  scala: SiScala,
  perl: SiPerl,
  r: SiR,
  lua: SiLua,
  julia: SiJulia,
  haskell: SiHaskell,
  elixir: SiElixir,
  erlang: SiErlang,
  clojure: SiClojure,
  ocaml: SiOcaml,
  fortran: SiFortran,
  solidity: SiSolidity,
  nim: SiNim,
  zig: SiZig,
  groovy: SiGroovy,
  html: SiHtml5,
  css: SiCss,
  scss: SiSass,
  sass: SiSass,
  sql: SiMysql,
  graphql: SiGraphql,
  node: SiNodedotjs,
  vue: SiVuedotjs,
  angular: SiAngular,
  svelte: SiSvelte,
  dockerfile: SiDocker,
  yaml: SiYaml,
  json: SiJson,
  markdown: SiMarkdown,
  shell: SiGnubash,
  bash: SiGnubash,
};

export function getLangIcon(language?: string | null): IconType {
  if (!language) return FileCode2;
  return ICONS[language.trim().toLowerCase()] ?? FileCode2;
}
