// Brand colors for popular languages (close to original brand/icon colors).
// Returns a stable color + emoji-like dot for an inline badge.
export type LangMeta = { color: string; label: string };

const MAP: Record<string, LangMeta> = {
  javascript: { color: "#f7df1e", label: "JavaScript" },
  typescript: { color: "#3178c6", label: "TypeScript" },
  tsx:        { color: "#3178c6", label: "TSX" },
  jsx:        { color: "#f7df1e", label: "JSX" },
  python:     { color: "#3776ab", label: "Python" },
  java:       { color: "#ea2d2e", label: "Java" },
  kotlin:     { color: "#7f52ff", label: "Kotlin" },
  swift:      { color: "#fa7343", label: "Swift" },
  go:         { color: "#00add8", label: "Go" },
  rust:       { color: "#dea584", label: "Rust" },
  c:          { color: "#a8b9cc", label: "C" },
  cpp:        { color: "#00599c", label: "C++" },
  csharp:     { color: "#178600", label: "C#" },
  fsharp:     { color: "#b845fc", label: "F#" },
  ruby:       { color: "#cc342d", label: "Ruby" },
  php:        { color: "#777bb4", label: "PHP" },
  html:       { color: "#e34c26", label: "HTML" },
  css:        { color: "#264de4", label: "CSS" },
  scss:       { color: "#cc6699", label: "SCSS" },
  sass:       { color: "#cc6699", label: "Sass" },
  json:       { color: "#cbcb41", label: "JSON" },
  yaml:       { color: "#cb171e", label: "YAML" },
  xml:        { color: "#e34c26", label: "XML" },
  markdown:   { color: "#083fa1", label: "Markdown" },
  shell:      { color: "#4eaa25", label: "Shell" },
  bash:       { color: "#4eaa25", label: "Bash" },
  powershell: { color: "#012456", label: "PowerShell" },
  sql:        { color: "#e38c00", label: "SQL" },
  dart:       { color: "#0175c2", label: "Dart" },
  elixir:     { color: "#6e4a7e", label: "Elixir" },
  erlang:     { color: "#b83998", label: "Erlang" },
  haskell:    { color: "#5e5086", label: "Haskell" },
  scala:      { color: "#dc322f", label: "Scala" },
  lua:        { color: "#000080", label: "Lua" },
  perl:       { color: "#0298c3", label: "Perl" },
  r:          { color: "#198ce7", label: "R" },
  julia:      { color: "#a270ba", label: "Julia" },
  objectivec: { color: "#438eff", label: "Objective-C" },
  solidity:   { color: "#aa6746", label: "Solidity" },
  vue:        { color: "#41b883", label: "Vue" },
  svelte:     { color: "#ff3e00", label: "Svelte" },
  graphql:    { color: "#e10098", label: "GraphQL" },
  dockerfile: { color: "#2496ed", label: "Docker" },
  toml:       { color: "#9c4221", label: "TOML" },
  ini:        { color: "#d1d1d1", label: "INI" },
  nix:        { color: "#7e7eff", label: "Nix" },
  zig:        { color: "#f7a41d", label: "Zig" },
  nim:        { color: "#ffe953", label: "Nim" },
  crystal:    { color: "#000100", label: "Crystal" },
  ocaml:      { color: "#3be133", label: "OCaml" },
  clojure:    { color: "#db5855", label: "Clojure" },
  groovy:     { color: "#4298b8", label: "Groovy" },
  prolog:     { color: "#74283c", label: "Prolog" },
  fortran:    { color: "#4d41b1", label: "Fortran" },
  cobol:      { color: "#4d41b1", label: "COBOL" },
  ada:        { color: "#02f88c", label: "Ada" },
  assembly:   { color: "#6e4c13", label: "Assembly" },
  vbnet:      { color: "#945db7", label: "VB.NET" },
  visualbasic:{ color: "#945db7", label: "Visual Basic" },
  plaintext:  { color: "#9ca3af", label: "Text" },
};

export function getLangMeta(language?: string | null): LangMeta {
  if (!language) return { color: "#9ca3af", label: "Text" };
  const key = language.trim().toLowerCase();
  return MAP[key] ?? { color: "#9ca3af", label: language };
}
